### ISSUE TITLE
Checking file permissions potentially not working

### ISSUE THREAD

**Issue by jpahullo** [amato-gianluca/docker-wims#3]
Hi @amato-gianluca,

Thanks for this great work.

After solving the other issue #2, now I wanted to make a quick verification of the system.

I have entered to the file permission checking and I always see this message:

![image](https://github.com/user-attachments/assets/ae5dcddd-28a6-460f-9369-b726bbdd11ca)

In text format:

```
WIMS HOME > WIMS SITE MAINTENANCE > FILE PERMISSION VERIFICATION(CURRENT)
WIMS site maintenance
File permission verification

Attention
If you use wims-chroot distribution, you must execute as root the script bin/setchroot.

If you use wimsd, you must execute as root the script bin/setwimsd.
```

I have verified that into the image we use the bin/setwimsd, but even that it is run into the image construction and also manually with the running container, I always see the above message.

I do not know which kind of response it could provide, but I would expect something like a positive message of the kind "All files permissions are ok" or similar. The above message keeps me thinking something potentially is not properly configured.

To build the image I use this docker-compose.yml file:

```yaml
services:
  app:
    image: amatogianluca/wims:4.26-1
    security_opt:
      - seccomp:unconfined
    hostname: wims
    restart: always
    #volumes:
    #  - ./wims:/home/wims/log:Z
    ports:
      - 10000:80
```

On some trial, I used a bind volume, but now I do not use any kind of volume to keep a clean container without files modified unintentionally from trial to trial.
